### ISSUE TITLE
Problem with Proxy

### ISSUE THREAD

**Issue by enriquegq** [dcarroll/sublime-lightning#10]
I've tried out the plugin and it works great but I faced some problem when trying to work through a proxy.

[Error] dial tcp: GetAddrInfoW: No such host is known.

Any suggestion/workaround?

**Comment by dcarroll** [comment]
Oh, uh no, I have no idea.

On Fri, May 29, 2015 at 2:43 AM, enriquegq <notifications@github.com> wrote:

> I've tried out the plugin and it works great but I faced some problem when
> trying to work through a proxy.
>
> [Error] dial tcp: GetAddrInfoW: No such host is known.
>
> Any suggestion/workaround?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dcarroll/sublime-lightning/issues/10>.
>



-- 
Thanks,
Dave
