### ISSUE TITLE
any plans to merge this with Mavensmate?

### ISSUE THREAD

**Issue by dbleier** [dcarroll/sublime-lightning#11]
This looks like a great tool. It would be awesome to merge with Mavensmate and have one app and access point for SFDC interactions.

(sorry if this is not really an "issue." just didn't know where else to post this question.)

**Comment by dcarroll** [comment]
I believe that Mavens Mate will eventually, if not already, have lightning functionality. From what I can tell, most of the effort is going into the Mavens Mate for Atom.io at this point. Also, the underlying Metadata API clients are different, Python for MM and Force CLI for sublime-lightning, so merging might be difficult.
