### ISSUE TITLE
Running 'Lightning > Fetch > Lightning' does not run command 

### ISSUE THREAD

**Issue by sayerpm** [dcarroll/sublime-lightning#12]
Just installed most recent package and choosing 'Lightning > Fetch > Lightning' is not working. Enabled logging and Console shows nothing, too. For reference, I see 'Running FetchMetaCommand' for the 'Fetch > Metadata' and 'Running FetchPackageCommand' for 'Fetch > Package', though nothing seems to happen for either, probably for legitimate reason (no folder structure or data). Thoughts?

**Comment by nelsonra** [comment]
Firstly make sure you have logged in. Once you're logged after clicking fetch lightning you should see a dropdown listing All Bundles and the individual bundles from your org. I'm new to this plugin in as well and found a lot of times just making sure I was logged in helped. 

I take it you have some lightning bundles in your org, if not maybe that's why it's not able to list any bundles to download.

I hope that helps.

**Comment by sayerpm** [comment]
Thanks for the quick reply! I am logged in. "Save login was  ok, Logged in as...."

**Comment by sayerpm** [comment]
@nelsonra Are you using v0.22.27 of the CLI?

**Comment by sayerpm** [comment]
May be a permissions issue with Sublime Text running the commands as the calls (show in logs) work in console *when I run as root user*. I dig a bit deeper on this. Thanks.

**Comment by nelsonra** [comment]
I'm actually running v0.22.26. 

Again do you have any resources created in your org? I only ask because you said "no folder structure or data".

Try adding a resource (App / Component / Event). Right click the aura folder Lightning > Create > App / Component / Event.

**Comment by sayerpm** [comment]
Yes, several. When I run from terminal I can do everything the plugin is doing via CLI.

**Comment by dcarroll** [comment]
I'll take a look this morning.

Dave Carroll

On Jun 25, 2015, at 6:17 AM, Sayer Martin <notifications@github.com> wrote:

Yes, several. When I run from terminal I can do everything the plugin is
doing via CLI.

—
Reply to this email directly or view it on GitHub
<https://github.com/dcarroll/sublime-lightning/issues/12#issuecomment-115254087>
.

**Comment by sayerpm** [comment]
Thanks Dave. A bit more info here - when running from a terminal window I get a successful login message, too, but on a subsequent call it errors out. I don't think the credential gets stored in this case. When I 'sudo' the calls to get that to store and everything to work. So the plugin issue could be login related because that credential is not being stored. Need to change permissions on my end?

**Comment by dcarroll** [comment]
The "credentials" are store in /Users/<username>/.force, so that should not
be an issue.  You can inspect that folder and you might uncover more info.

On Thu, Jun 25, 2015 at 10:26 AM, Sayer Martin <notifications@github.com>
wrote:

> Thanks Dave. A bit more info here - when running from a terminal window I
> get a successful login message, too, but on a subsequent call it errors
> out. I don't think the credential gets stored in this case. When I 'sudo'
> the calls to get that to store and everything to work. So the plugin issue
> could be login related because that credential is not being stored. Need to
> change permissions on my end?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dcarroll/sublime-lightning/issues/12#issuecomment-115334053>
> .
>



-- 
Thanks,
Dave
