### ISSUE TITLE
Cannot fully fetch the component and Duplicate Id error

### ISSUE THREAD

**Issue by megatran** [dcarroll/sublime-lightning#13]
1. The plugin cannot fully fetch the newly created components anymore. Whenever I create a new component in the online dev console, the lightning plugin only creates the file ".manifest" containing the component's name, id. For example {"Name":"ManagerDashBoard","Id":"0Ab110000004CYhCAM","Files":[]}

2. The plugin cannot modify/update some existing components on the local computer. The error is "duplicate value found: AuraDefinitionBundleId duplicaes value on record with id###...etc" (please see attached picture). I think the plugin gets confused when I save the file locally. Usually, whenever I saved the file in sublime, the file on the server got updated immediately.

**Comment by dcarroll** [comment]
I am unable to reproduce this issue.  Please ensure you are using the latest version of the plugin and the latest version of the Force CLI.
