### ISSUE TITLE
fetch lightning yields ERROR at Row:1:Column:77 unexpected token: --

### ISSUE THREAD

**Issue by westhechiang** [dcarroll/sublime-lightning#21]
![image](https://cloud.githubusercontent.com/assets/7388796/10501776/840fe200-7299-11e5-9f40-8234bde2469f.png)

It was working maybe an hour or two ago but now it's not working.

**Comment by westhechiang** [comment]
Currently on version v0.22.27. Going to try to update and see what happens.

**Comment by dcarroll** [comment]
Don't update. You need to down grade the plugin.

I made a mistake and am trying to unravel it know.

On Wed, Oct 14, 2015 at 5:36 PM, Wesley Chiang <notifications@github.com>
wrote:

> Currently on version v0.22.27. Going to try to update and see what happens.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dcarroll/sublime-lightning/issues/21#issuecomment-148241643>
> .
>



-- 
Thanks,
Dave

**Comment by westhechiang** [comment]
ah I see. good to know. Which version do you recommend?

**Comment by dcarroll** [comment]
Until package control sees the latest release, you can use the package directly from this repo by setting a Package Control/Settings/User using below:

`{
	"bootstrapped": true,
	"in_process_packages":
	[
	],
	"installed_packages":
	[
		"Indent XML",
		"Package Control",
		"Python Flake8 Lint"
	],
	"repositories":
	[
		"https://github.com/dcarroll/sublime-lightning"
	]
}
`

**Comment by dcarroll** [comment]
You can pull the one from github, I put instructions in the issue.

Sorry!!

On Wed, Oct 14, 2015 at 5:48 PM, Wesley Chiang <notifications@github.com>
wrote:

> ah I see. good to know. Which version do you recommend?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dcarroll/sublime-lightning/issues/21#issuecomment-148242985>
> .
>



-- 
Thanks,
Dave

**Comment by dcarroll** [comment]
Updating latest CLI and plugin should resolve.
