### ISSUE TITLE
Unable to fetch Lightning components from Sandbox

### ISSUE THREAD

**Issue by donmac23** [dcarroll/sublime-lightning#22]
Been trying to get Lightning in Sublime but it's not happening...

I've followed the steps on [this page](http://www.forcewizard.com/blog/installing-mavensmate-windows-lightning-support) to install. I have version 6.0.0 of Mavensmate, build 3083 of Sublime Text 3 and v 0.22.36 of force.exe saved in the Sublime Progam Files folder. Running Windows 7. I have tried going through Lightning/Login first and entering the details and it tells me it has successfully logged in. However, when I go to fetch Lightning, it reports an error "panic: runtime error: invalid memory address or nil point dereference". I can write more of the error message if that's helpful but haven't right now because I can't copy paste and it's a lot to type...

**Comment by dcarroll** [comment]
The Lightning sublime plugin has no dependencies on Mavensmate.  I would be
good to get more of the error message.

On Wed, Oct 21, 2015 at 3:39 PM, donmac23 <notifications@github.com> wrote:

> Been trying to get Lightning in Sublime but it's not happening...
>
> I've followed the steps on this page
> <http://www.forcewizard.com/blog/installing-mavensmate-windows-lightning-support>
> to install. I have version 6.0.0 of Mavensmate, build 3083 of Sublime Text
> 3 and v 0.22.36 of force.exe saved in the Sublime Progam Files folder.
> Running Windows 7. I have tried going through Lightning/Login first and
> entering the details and it tells me it has successfully logged in.
> However, when I go to fetch Lightning, it reports an error "panic: runtime
> error: invalid memory address or nil point dereference". I can write more
> of the error message if that's helpful but haven't right now because I
> can't copy paste and it's a lot to type...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dcarroll/sublime-lightning/issues/22>.
>



-- 
Thanks,
Dave

**Comment by donmac23** [comment]
Sorry, it looks like it is not specifically this Lightning plugin where the error occurs. I tried running the force.exe separately and I get the same error, so I guess it must be something to do with that. Here is the error message I get (occurs when I run various other commands too):

    C:\Program Files\Sublime Text 3>force fetch -t Aura ProductInventory -d "/Users/
chdmcint/workspace/Seafood Lightning"
    panic: runtime error: invalid memory address or nil pointer dereference [signal 0xc0000005 code=0x1 addr=0x0 pc=0x4238de]

    goroutine 16 [running]:
    runtime.panic(0x804b60, 0xabb3e2)
        /tmp/build_f8ba0f4168b936fea1eb59aef85c032b/go/src/pkg/runtime/panic.c:2
79 +0x11f
    main.(*Force).GetAuraBundlesList(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x
0, ...)
        /app/vendor/lib/go/src/src/github.com/heroku/force/force.go:573 +0x2ae
main.(*Force).GetAuraBundles(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, .
..)
        /app/vendor/lib/go/src/src/github.com/heroku/force/force.go:521 +0x8a
main.runFetchAura2(0xab98e0, 0x8500f0, 0x0)
        /app/vendor/lib/go/src/src/github.com/heroku/force/fetch.go:84 +0x85
main.runFetch(0xab98e0, 0xc08201e0b0, 0x3, 0x3)
        /app/vendor/lib/go/src/src/github.com/heroku/force/fetch.go:203 +0x1baa
main.main()
        /app/vendor/lib/go/src/src/github.com/heroku/force/main.go:55 +0x2b1

    goroutine 19 [finalizer wait]:
    runtime.park(0x47b3e0, 0xac03a8, 0xabe489)
        /tmp/build_f8ba0f4168b936fea1eb59aef85c032b/go/src/pkg/runtime/proc.c:13
69 +0xac
    runtime.parkunlock(0xac03a8, 0xabe489)
        /tmp/build_f8ba0f4168b936fea1eb59aef85c032b/go/src/pkg/runtime/proc.c:13
85 +0x42
    runfinq()
        /tmp/build_f8ba0f4168b936fea1eb59aef85c032b/go/src/pkg/runtime/mgc0.c:26
44 +0xdd
    runtime.goexit()
        /tmp/build_f8ba0f4168b936fea1eb59aef85c032b/go/src/pkg/runtime/proc.c:14
45

**Comment by dcarroll** [comment]
Might be something with the way the path is specified. Windows is different
than Mac or Unix.  I won't be able to test and debug this until next week.

On Thu, Oct 22, 2015 at 2:54 PM, donmac23 <notifications@github.com> wrote:

> Sorry, it looks like it is not specifically this Lightning plugin where
> the error occurs. I tried running the force.exe separately and I get the
> same error, so I guess it must be something to do with that. Here is the
> error message I get (occurs when I run various other commands too):
>
> C:\Program Files\Sublime Text 3>force fetch -t Aura ProductInventory -d "/Users/
>
> chdmcint/workspace/Seafood Lightning"
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal 0xc0000005 code=0x1 addr=0x0 pc=0x4238de]
>
> goroutine 16 [running]:
> runtime.panic(0x804b60, 0xabb3e2)
>     /tmp/build_f8ba0f4168b936fea1eb59aef85c032b/go/src/pkg/runtime/panic.c:2
>
> 79 +0x11f
> main.(
>
>
> *Force).GetAuraBundlesList(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x
> 0, ...) /app/vendor/lib/go/src/src/github.com/heroku/force/force.go:573
> <http://github.com/heroku/force/force.go:573> +0x2ae main.(*Force).GetAuraBundles(0x0,
> 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, .
> ..)
> /app/vendor/lib/go/src/src/github.com/heroku/force/force.go:521 +0x8a
> main.runFetchAura2(0xab98e0, 0x8500f0, 0x0)
> /app/vendor/lib/go/src/src/github.com/heroku/force/fetch.go:84 +0x85
> main.runFetch(0xab98e0, 0xc08201e0b0, 0x3, 0x3)
> /app/vendor/lib/go/src/src/github.com/heroku/force/fetch.go:203 +0x1baa
> main.main()
> /app/vendor/lib/go/src/src/github.com/heroku/force/main.go:55 +0x2b1
>
> goroutine 19 [finalizer wait]:
> runtime.park(0x47b3e0, 0xac03a8, 0xabe489)
>     /tmp/build_f8ba0f4168b936fea1eb59aef85c032b/go/src/pkg/runtime/proc.c:13
>
> 69 +0xac
> runtime.parkunlock(0xac03a8, 0xabe489)
> /tmp/build_f8ba0f4168b936fea1eb59aef85c032b/go/src/pkg/runtime/proc.c:13
> 85 +0x42
> runfinq()
> /tmp/build_f8ba0f4168b936fea1eb59aef85c032b/go/src/pkg/runtime/mgc0.c:26
> 44 +0xdd
> runtime.goexit()
> /tmp/build_f8ba0f4168b936fea1eb59aef85c032b/go/src/pkg/runtime/proc.c:14
> 45
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dcarroll/sublime-lightning/issues/22#issuecomment-150367109>
> .
>



-- 
Thanks,
Dave

**Comment by dcarroll** [comment]
I've tested this in a Sandbox environment with the latest CLI and Sublime plugin without any problems.  Please try updating the CLI and plugin and re-open if it is still an issue.

**Comment by donmac23** [comment]
thanks @dcarroll it's working for me now

**Comment by donmac23** [comment]
Dang, I have this problem again. Noticed it a while ago and ignored it but now I went through all the steps and grabbed the latest force CLI and retried. Still get the nil pointer reference. I am using the Windows 64 bit version, v.0.22.50. I can login to sandbox OK but when I try to fetch lightning component via command line I get a similar error to the above:
`C:\dev\tools\forcecli>force fetch -t Aura -n InventoryList -d "C:\Users\chdmcint\workspace\lightning"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x0 pc=0x42b982]

goroutine 1 [running]:
main.(*Force).GetAuraBundleByName(0x0, 0xc082002310, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/heroku/force/force.go:499 +0x592
main.(*Force).GetAuraBundle(0x0, 0xc082002310, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/heroku/force/force.go:487 +0xb3
main.runFetchAura2(0xba1e80, 0xc082002310, 0xd)
        /home/travis/gopath/src/github.com/heroku/force/fetch.go:89 +0x164
main.runFetch(0xba1e80, 0xc082056070, 0x0, 0x0)
        /home/travis/gopath/src/github.com/heroku/force/fetch.go:200 +0x1aa
main.main()
        /home/travis/gopath/src/github.com/heroku/force/main.go:55 +0x2f9
`

**Comment by dcarroll** [comment]
Try dropping the -d.

Dave Carroll

On Feb 24, 2016, at 2:33 PM, donmac23 <notifications@github.com> wrote:

Dang, I have this problem again. Noticed it a while ago and ignored it but
now I went through all the steps and grabbed the latest force CLI and
retried. Still get the nil pointer reference. I am using the Windows 64 bit
version, v.0.22.50. I can login to sandbox OK but when I try to fetch
lightning component via command line I get a similar error to the above:
`C:\dev\tools\forcecli>force fetch -t Aura -n InventoryList -d
"C:\Users\chdmcint\workspace\lightning"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x0 pc=0x42b982]

goroutine 1 [running]:
main.(

*Force).GetAuraBundleByName(0x0, 0xc082002310, 0xd, 0x0, 0x0, 0x0, 0x0,
0x0, 0x0, 0x0, ...)
/home/travis/gopath/src/github.com/heroku/force/force.go:499
<http://github.com/heroku/force/force.go:499> +0x592
main.(*Force).GetAuraBundle(0x0,
0xc082002310, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/home/travis/gopath/src/github.com/heroku/force/force.go:487 +0xb3
main.runFetchAura2(0xba1e80, 0xc082002310, 0xd)
/home/travis/gopath/src/github.com/heroku/force/fetch.go:89 +0x164
main.runFetch(0xba1e80, 0xc082056070, 0x0, 0x0)
/home/travis/gopath/src/github.com/heroku/force/fetch.go:200 +0x1aa
main.main()
/home/travis/gopath/src/github.com/heroku/force/main.go:55 +0x2f9
`

—
Reply to this email directly or view it on GitHub
<https://github.com/dcarroll/sublime-lightning/issues/22#issuecomment-188488885>
.

**Comment by donmac23** [comment]
Dropping -d has same result :(

**Comment by ArianYousefi** [comment]
Go to you command line and type force login and then complete the OAuth flow and close the browser. Make sure you login to the same org you need to fetch the Lightning Components. then go to sublime and right click on src and fetch the components.
