### ISSUE TITLE
Can this plug-In use in Windows?

### ISSUE THREAD

**Issue by yebin245** [dcarroll/sublime-lightning#23]
This Plug-In can use in Windows System or not ?

**Comment by dcarroll** [comment]
Yes

On Wed, Nov 4, 2015 at 2:20 AM, yebin245 <notifications@github.com> wrote:

> This Plug-In can use in Windows System or not ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dcarroll/sublime-lightning/issues/23>.
>



-- 
Thanks,
Dave
