### ISSUE TITLE
Unable to switch end points

### ISSUE THREAD

**Issue by justintieu** [dcarroll/sublime-lightning#24]
I have two different lightning orgs that I work on. I was trying to do some work on the other one, but it still showed the end point of the first one even though I gave a different instance url. 

There doesn't seem to be anything that documents how to change end points.

**Comment by dcarroll** [comment]
One thing you can do is to login to the orgs using the command line.  The sublime plugin uses the CLI behind the scenes and the CLI manages the sessions for Sublime.

**Comment by justintieu** [comment]
Thanks for answering. I'll do that then.
