### ISSUE TITLE
Support for 32 bit Windows 7 system

### ISSUE THREAD

**Issue by raJSN** [dcarroll/sublime-lightning#25]
Current release is not supported on win 7 32 bit system. Do we have any available solution for 32 bit system. 
I want to code lightning...

**Comment by raJSN** [comment]
![image](https://cloud.githubusercontent.com/assets/3901703/12552816/fa4978ae-c399-11e5-8e21-016943c269f5.png)

**Comment by dcarroll** [comment]
You can find the x386 version of the force.exe file here.
https://github.com/heroku/force/releases/download/v0.22.41/force.exe


On Mon, Jan 25, 2016 at 5:59 AM, RajendraSinghNagar <
notifications@github.com> wrote:

> [image: image]
> <https://cloud.githubusercontent.com/assets/3901703/12552816/fa4978ae-c399-11e5-8e21-016943c269f5.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dcarroll/sublime-lightning/issues/25#issuecomment-174516525>
> .
>



-- 
Thanks,
Dave

**Comment by raJSN** [comment]
Thanks Dave.
