### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by jpoozhik** [dcarroll/sublime-lightning#27]
Hi Dave,

When I login using login lightning it has an error

Loaded Endpoint: (https://login.salesforce.com)
ERROR: Cannot GET /auth/soaplogin/?id=https://login.salesforce.com

I tried this with several different orgs and I get the same issue.

Thanks,
Joe

**Comment by dcarroll** [comment]
This is an issue I created with a related logging server, should be resolved with a rollback in about an hour. Apologies.

Dave Carroll

**Comment by jpoozhik** [comment]
Thank you Dave. It works. By the way its a great plugin.

Just a thought may be someday it can create a package for deployment.

Kind Regards,
Joe
