### ISSUE TITLE
Right-click menu has typo and all commands are greyed out

### ISSUE THREAD

**Issue by ErnstEeldert** [dcarroll/sublime-lightning#5]
I seem to be having trouble getting the Lightning plugin to work. I have force installed:

$ force version
v0.22.16

It is logged in:

$ force active
eeeldert@ltng.org - https://gs0.salesforce.com - ns:aotpee

It is in my path:

$ which force
/usr/local/bin/force

But still all items in the right-click menu are greyed out. On a side note, the top level menu item is misspelled 'Lighting'.

Any ideas?
![screen shot 2015-02-13 at 17 24 28](https://cloud.githubusercontent.com/assets/8919203/6190873/7285e0e2-b3a5-11e4-9d5d-a84a945ee34f.png)

**Comment by dcarroll** [comment]
The folder structure is important. Where you have src/aura/etc it needs to be metadata/aura/etc.

Yes, it's a bit brittle in that sense, so if you have any suggestions I'm open.

**Comment by ErnstEeldert** [comment]
Aah, I see. The reason the code sits in src is because that is MavensMate's default. I tried again with a blank folder, as per the readme instructions, and created a metadata/aura subfolder. Whatever folder I click, all commands are greyed out.

**Comment by dcarroll** [comment]
Hmm... can you try downloading the latest version of the Force CLI?  Latest version is 0.22.18.
http://force-cli.herokuapp.com/

**Comment by ErnstEeldert** [comment]
Now it works! Thanks for digging into this so quickly!

**Comment by dcarroll** [comment]
Oh  good!  Any feedback is welcome.
