### ISSUE TITLE
Not able to add css to existing component

### ISSUE THREAD

**Issue by victorabraham** [dcarroll/sublime-lightning#52]
When i am trying to add css to an existing component named "Sample", it is not getting added. Nothing is being shown below. If we open console, I am getting below error,
FileNotFoundError: [Errno 2] No such file or directory: '/Users/myName/Documents/Trainings/lightning/projectName/metadata/aura/SampleStyle/SampleStyle.css'

It should try to find file under below path right?

'/Users/myName/Documents/Trainings/lightning/projectName/metadata/aura/Sample/SampleStyle.css'

**Comment by dcarroll** [comment]
Well, that's a bug, looking now.

**Comment by victorabraham** [comment]
@dcarroll - Thank you for the quick reply
