### ISSUE TITLE
unable to create component if root folder name contains space

### ISSUE THREAD

**Issue by ErnstEeldert** [dcarroll/sublime-lightning#6]
$ mkdir -p some\ folder/metadata/aura
$ subl some\ folder/
Right-click aura -> Lightning -> Create Component -> provide name

No component is created. The output pane says the following:

ERROR: File does not exist
/Users/eeeldert/Downloads/some
stat /Users/eeeldert/Downloads/some: no such file or directory
[Finished in 0.0s with exit code 1]
[cmd: ['force', 'aura', 'push -f=/Users/eeeldert/Downloads/some folder/metadata/aura/mycomp/mycomp.cmp']]
[dir: /Users/eeeldert/Downloads/some folder/metadata/aura/mycomp]

**Comment by dcarroll** [comment]
I may not be handling the space in the file path. Try removing the space?

**Comment by ErnstEeldert** [comment]
Hmm, red herring alert. Even though it shows the error in the console, the
component is created as expected. Did a few more tests, and everything is
coming through fine.

Case closed!

**Comment by dcarroll** [comment]
Weird, I think I need to look at handling spaces in the file path though.

Thanks!
