### ISSUE TITLE
Create or Retreive Lightning Components from Sandbox

### ISSUE THREAD

**Issue by jimrae** [dcarroll/sublime-lightning#7]
Appears that there is no ability to use against a sandbox org, as the instance parameter for the force CLI cannot be passed, and defaults to Production.  Could an enhancement be added to allow specifying the Test or Production Instance for the login function?

**Comment by dcarroll** [comment]
Hmm... Good point. Although the underlying force cli supports it, no way to specify in Sublime.

A workaround is to drop into the command line and login there to sandbox.  You should then be able to use Sublime for sandbox.

I'll see what a good way might be to get that instance as another piece of data to the login call.

**Comment by enriquegq** [comment]
@jimrae you can click on login and instead of writing the username, hit the enter button. The login workflow will be open on the browser and simply change in the URL **login**.salesforce.com for **test**.salesforce.com
Then enter your credentials for sandbox et voilà!

**Comment by ukoya** [comment]
Hi there I know this is "old" but i modified the plugin to ask for the instance after the credentials (username, password and then instance url) I can send a pull request if you want to take a look.

Regards,
Jonathan

**Comment by dcarroll** [comment]
@ukoya do please send a pull request!

**Comment by dcarroll** [comment]
The most reliable way to do this is to try to login and supply no username or password.  You will get to a browser login screen.  Replace "login.salesforce.com" with "test.salesforce.com" and leave the rest of the url.  You will now go through the entire OAuth and be logged in to Sandbox.
