### ISSUE TITLE
Duplicate component error while pushing the component to Salesforce

### ISSUE THREAD

**Issue by rakesh2020** [dcarroll/sublime-lightning#9]
A component has been created in the salesforce using the dev console.
The same has been fetched to sublime and then when try to modify the component and save the file.

The following error is thrown

- The error is:  duplicate value found: AuraDefinitionBundleId duplicates value on record with id: 0Adj00000004p4r
ERROR: duplicate value found: AuraDefinitionBundleId duplicates value on record with id: 0Adj00000004p4r
%!(EXTRA string=DUPLICATE_VALUE)[Finished in 0.9s]

Environment: Windows 7, Sublime Text 3

**Comment by dcarroll** [comment]
Maybe, delete the physical folder and refetch the component.

On Mon, May 4, 2015 at 8:07 AM, Rakesh <notifications@github.com> wrote:

> A component has been created in the salesforce using the dev console.
> The same has been fetched to sublime and then when try to modify the
> component and save the file.
>
> The following error is thrown
>
>    - The error is: duplicate value found: AuraDefinitionBundleId
>    duplicates value on record with id: 0Adj00000004p4r ERROR: duplicate value
>    found: AuraDefinitionBundleId duplicates value on record with id:
>    0Adj00000004p4r %!(EXTRA string=DUPLICATE_VALUE)[Finished in 0.9s]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dcarroll/sublime-lightning/issues/9>.
>



-- 
Thanks,
Dave

**Comment by rakesh2020** [comment]
Thanks Dave ☺
Deleting the local folder and re fetching the bundle worked.
